name: Sonatype publication with Gradle

on:
  release:
    types: [released]

jobs:
  sonatype-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      #Run JDK configuration
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 8

      #Gradle cache configuration
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      #Authorizing gradlew files
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      #Build project
      - name: Build with Gradle
        run: ./gradlew build

      #After decoding the secret key, place the file in / tmp / secring.gpg
      - name: Decode
        run: |
          echo "${{secrets.SIGNING_SECRET_KEY_RING_FILE}}" > ~/.gradle/secring.gpg.b64
          base64 -d ~/.gradle/secring.gpg.b64 > ~/.gradle/secring.gpg

      #Publish project
      - name: Publish DeviceSDK
        run: ./gradlew DeviceSDK:publish -Psigning.secretKeyRingFile=$(echo ~/.gradle/secring.gpg)
        env:
          OSSRH_USERNAME: ${{secrets.OSSRH_USERNAME}}
          OSSRH_PASSWORD: ${{secrets.OSSRH_PASSWORD}}
          SONATYPE_STAGING_PROFILE_ID: ${{secrets.SONATYPE_STAGING_PROFILE_ID}}
          SIGNING_KEY_ID: ${{secrets.SIGNING_KEY_ID}}
      - name: Publish DeviceSDKAndroid -Psigning.secretKeyRingFile=$(echo ~/.gradle/secring.gpg)
        run: ./gradlew DeviceSDKAndroid:publish
        env:
          OSSRH_USERNAME: ${{secrets.OSSRH_USERNAME}}
          OSSRH_PASSWORD: ${{secrets.OSSRH_PASSWORD}}
          SONATYPE_STAGING_PROFILE_ID: ${{secrets.SONATYPE_STAGING_PROFILE_ID}}
          SIGNING_KEY_ID: ${{secrets.SIGNING_KEY_ID}}
      - name: Publish DeviceSDKGeneric
        run: ./gradlew DeviceSDKGeneric:publish -Psigning.secretKeyRingFile=$(echo ~/.gradle/secring.gpg)
        env:
          OSSRH_USERNAME: ${{secrets.OSSRH_USERNAME}}
          OSSRH_PASSWORD: ${{secrets.OSSRH_PASSWORD}}
          SONATYPE_STAGING_PROFILE_ID: ${{secrets.SONATYPE_STAGING_PROFILE_ID}}
          SIGNING_KEY_ID: ${{secrets.SIGNING_KEY_ID}}
